-- 07_seed_subjects.sql : 38 môn học
USE diem_thi;

INSERT INTO subjects (id, subject_code, subject_name, credits, department_id, description) VALUES
(1, 'IT001', 'Lập trình C++', 3, 1, 'Môn học Lập trình C++'),
(2, 'IT002', 'Cơ sở dữ liệu', 3, 1, 'Môn học Cơ sở dữ liệu'),
(3, 'IT003', 'Lập trình Web', 3, 1, 'Môn học Lập trình Web'),
(4, 'IT004', 'Cấu trúc dữ liệu và giải thuật', 4, 1, 'Môn học Cấu trúc dữ liệu và giải thuật'),
(5, 'IT005', 'Lập trình Java', 3, 1, 'Môn học Lập trình Java'),
(6, 'IT006', 'Công nghệ phần mềm', 3, 3, 'Môn học Công nghệ phần mềm'),
(7, 'IT007', 'Hệ điều hành', 3, 1, 'Môn học Hệ điều hành'),
(8, 'IT008', 'Mạng máy tính', 3, 9, 'Môn học Mạng máy tính'),
(9, 'IT009', 'Trí tuệ nhân tạo', 3, 1, 'Môn học Trí tuệ nhân tạo'),
(10, 'IT010', 'Xử lý ảnh', 3, 1, 'Môn học Xử lý ảnh'),
(11, 'IT011', 'Đồ họa máy tính', 3, 1, 'Môn học Đồ họa máy tính'),
(12, 'IT012', 'An toàn thông tin', 3, 4, 'Môn học An toàn thông tin'),
(13, 'IT013', 'Phân tích thiết kế hệ thống', 3, 1, 'Môn học Phân tích thiết kế hệ thống'),
(14, 'IT014', 'Phát triển ứng dụng di động', 3, 3, 'Môn học Phát triển ứng dụng di động'),
(15, 'IT015', 'Truyền thông đa phương tiện', 2, 1, 'Môn học Truyền thông đa phương tiện'),
(16, 'IT016', 'Kiến trúc máy tính', 3, 2, 'Môn học Kiến trúc máy tính'),
(17, 'IT017', 'Nhập môn lập trình', 3, 1, 'Môn học Nhập môn lập trình'),
(18, 'IT018', 'Lập trình hướng đối tượng', 3, 1, 'Môn học Lập trình hướng đối tượng'),
(19, 'IT019', 'Khai phá dữ liệu', 3, 1, 'Môn học Khai phá dữ liệu'),
(20, 'IT020', 'Điện toán đám mây', 2, 1, 'Môn học Điện toán đám mây'),
(21, 'BM001', 'Toán cao cấp 1', 3, 10, 'Môn học Toán cao cấp 1'),
(22, 'BM002', 'Toán cao cấp 2', 3, 10, 'Môn học Toán cao cấp 2'),
(23, 'BM003', 'Xác suất thống kê', 3, 10, 'Môn học Xác suất thống kê'),
(24, 'BM004', 'Tiếng Anh 1', 2, 8, 'Môn học Tiếng Anh 1'),
(25, 'BM005', 'Tiếng Anh 2', 2, 8, 'Môn học Tiếng Anh 2'),
(26, 'BM006', 'Tiếng Anh chuyên ngành', 2, 8, 'Môn học Tiếng Anh chuyên ngành'),
(27, 'BM007', 'Kinh tế học đại cương', 2, 10, 'Môn học Kinh tế học đại cương'),
(28, 'BM008', 'Pháp luật đại cương', 2, 10, 'Môn học Pháp luật đại cương'),
(29, 'BM009', 'Giáo dục thể chất 1', 1, 10, 'Môn học Giáo dục thể chất 1'),
(30, 'BM010', 'Giáo dục thể chất 2', 1, 10, 'Môn học Giáo dục thể chất 2'),
(31, 'BM011', 'Triết học Mác - Lênin', 3, 10, 'Môn học Triết học Mác - Lênin'),
(32, 'BM012', 'Kỹ năng mềm', 1, 5, 'Môn học Kỹ năng mềm'),
(33, 'KT001', 'Nguyên lý kế toán', 3, 7, 'Môn học Nguyên lý kế toán'),
(34, 'KT002', 'Kế toán tài chính', 3, 7, 'Môn học Kế toán tài chính'),
(35, 'TC001', 'Tài chính doanh nghiệp', 3, 6, 'Môn học Tài chính doanh nghiệp'),
(36, 'TC002', 'Thị trường chứng khoán', 2, 6, 'Môn học Thị trường chứng khoán'),
(37, 'QT001', 'Quản trị học', 3, 5, 'Môn học Quản trị học'),
(38, 'QT002', 'Marketing căn bản', 2, 5, 'Môn học Marketing căn bản');

